ifndef ASTRO_HOME
	$(error ASTRO_HOME environment variable not set)
endif

#Workaround to remove Makefile.vars, remove later
NO_ZLIB := 1

#A variável abaixo determina que os arquivos serão copiados para as pastas públicas ao invés de seus links simbólicos se tiver o valor "copy"
ASTRO_COPY_OR_LINK_BIN_LIB_INC ?= copy

PROCESSOR ?= x86_64
NVCC ?= nvcc
CC ?= gcc
CXX ?= g++
LINK ?= $(CXX)

AR = gcc-ar-$(shell $(CC) -dumpversion) cr
RANLIB = gcc-ranlib-$(shell $(CC) -dumpversion)

RM = rm -rf
CP = cp -f
LN = ln -s
NEWER = cmp -s
TOUCH = touch
MKDIR = mkdir -p
ECHO = @echo
DOXYGEN = doxygen

ifndef ASTRO_LOUD
SILENT = +@
MAKEFLAGS += -s
else
SILENT = +
export ASTRO_LOUD
endif

ifndef SO_DISTRO
SO_DISTRO=$(shell cat /etc/*-release | head -1)
endif

SRC_DIR = $(ASTRO_HOME)/src
INC_DIR = $(ASTRO_HOME)/include
LIB_DIR = $(ASTRO_HOME)/lib
SHARED_DIR = $(ASTRO_HOME)/lib
BIN_DIR = $(ASTRO_HOME)/bin
MAN_DIR = $(ASTRO_HOME)/man
DOC_DIR = $(ASTRO_HOME)/doc
GLADE_DIR = $(ASTRO_HOME)/data/gui

GLOBAL_INC_DIR = $(INSTALL_PATH)/include
GLOBAL_SHARED_DIR = $(INSTALL_PATH)/lib
GLOBAL_LIB_DIR = $(INSTALL_PATH)/lib
GLOBAL_BIN_DIR = $(INSTALL_PATH)/bin
GLOBAL_MAN_DIR = $(INSTALL_PATH)/man

pathsearch = $(firstword $(wildcard $(addsuffix /$(1),$(subst :, ,$(PATH)))))

# Warning: There are many distinct standards in use across all projects
# CFLAGS += -std=c11
# CXXFLAGS += -std=c++11

CFLAGS += -pipe -D_REENTRANT -D_LARGEFILE64_SOURCE `getconf LFS_CFLAGS`
CXXFLAGS += -pipe -D_REENTRANT -D_LARGEFILE64_SOURCE `getconf LFS_CFLAGS`

ifndef ASTRO_MINIMAL
CFLAGS +=  -Wall -Wextra -Wnull-dereference -Wsign-compare -Wlogical-op -Wno-unused-result
CXXFLAGS += -Wall -Wextra -Wnull-dereference -Wsign-compare -Wlogical-op -Wno-unused-result

ifeq (x86_64,$(PROCESSOR))
ifeq ($(shell expr $(shell $(CC) -dumpversion) \>= 11), 1)
CFLAGS += -march=x86-64-v3
else
#AVX uses VEX-prefixed replacements for SSE/MMX
#However, -mmmx/-msse* are still needed to enable related macros (e.g. __SSE4_2__)
CFLAGS += -mmmx -msse -msse2 -msse3 -mssse3 -msse4 \
-mavx -mavx2 -mbmi -mbmi2 -mf16c -mfma -mlzcnt -mmovbe -mpopcnt -msahf -mcx16 -mxsave
endif
ifeq ($(shell expr $(shell $(CXX) -dumpversion) \>= 11), 1)
CXXFLAGS += -march=x86-64-v3
else
CXXFLAGS += -mmmx -msse -msse2 -msse3 -mssse3 -msse4 \
-mavx -mavx2 -mbmi -mbmi2 -mf16c -mfma -mlzcnt -mmovbe -mpopcnt -msahf -mcx16 -mxsave
endif
endif

FOUTC := -ffunction-sections -fdata-sections

ifdef ASTRO_DEBUG
CFLAGS += -Wduplicated-cond -Wshadow -Wconversion -Wfloat-equal -ggdb3 -DDEBUG -ffp-contract=on
CXXFLAGS += -Wduplicated-cond -Wshadow -Wconversion -Wfloat-equal -ggdb3 -DDEBUG -ffp-contract=on
ifdef ASTRO_DO0
CFLAGS += -O0
CXXFLAGS += -O0
else ifdef ASTRO_DO3
CFLAGS += -O3 -fvar-tracking-assignments
CXXFLAGS += -O3 -fvar-tracking-assignments
else
CFLAGS += -Og -fno-omit-frame-pointer -fno-inline -fno-merge-constants -fno-delete-null-pointer-checks \
-fvar-tracking-assignments -fno-tree-dce
CXXFLAGS += -Og -fno-omit-frame-pointer -fno-inline -fno-merge-constants -fno-delete-null-pointer-checks \
-fvar-tracking-assignments -fno-tree-dce
endif
else
CFLAGS += -O3 -ffp-contract=fast $(FOUTC)
CXXFLAGS += -O3 -ffp-contract=fast $(FOUTC)
LFLAGS += -Wl,--gc-sections
ifeq ($(shell expr $(shell $(CC) -dumpversion) \>= 10), 1)
CFLAGS += -flto=auto -fuse-linker-plugin -fipa-pta
endif
ifeq ($(shell expr $(shell $(CXX) -dumpversion) \>= 10), 1)
CXXFLAGS += -flto=auto -fuse-linker-plugin -fipa-pta
endif
endif

else #ASTRO_MINIMAL
CFLAGS += -w -O0 -g0 -fmax-errors=1 -ffp-contract=off
CXXFLAGS += -w -O0 -g0 -fmax-errors=1 -ffp-contract=off
endif

ifdef FOUND_SUSE
CFLAGS += -finline-limit=2000 -DFOUND_SUSE
##-DCOMPILE_WITHOUT_CAMERA_SUPPORT
CXXFLAGS += -finline-limit=2000
##-DCOMPILE_WITHOUT_CAMERA_SUPPORT
endif

ifdef ASTRO_MEMORY_DEBUG
CFLAGS += -DASTRO_MEMORY_DEBUG
LFLAGS += -ldmalloc
endif

IFLAGS += -I$(INC_DIR)
LFLAGS += -L$(LIB_DIR) -L/usr/local/lib -L/usr/lib64 $(USER_LIBS) -lpthread -lm
LFLAGS += `getconf LFS_LDFLAGS`

ifdef IPC_DIR
CFLAGS += -DEXTERNAL_IPC
CXXFLAGS += -DEXTERNAL_IPC
IFLAGS += -I$(IPC_DIR)/include
LFLAGS += -L$(IPC_DIR)/lib/Linux-3.2
endif

ifdef NO_GRAPHICS
CFLAGS += -DNO_GRAPHICS
CXXFLAGS += -DNO_GRAPHICS
else
CFLAGS += -DHAVE_GRAPHICS
CXXFLAGS += -DHAVE_GRAPHICS
endif

ifdef NO_JOYSTICK
CFLAGS += -DNO_JOYSTICK
CXXFLAGS += -DNO_JOYSTICK
else
CFLAGS += -DHAVE_JOYSTICK
CXXFLAGS += -DHAVE_JOYSTICK
endif

ifdef NO_TCPD
CFLAGS += -DNO_TCPD
CXXFLAGS += -DNO_TCPD
else
CFLAGS += -DHAVE_TCPD
CXXFLAGS += -DHAVE_TCPD
endif

ifdef NO_LIBJPEG
CFLAGS += -DNO_LIBJPEG
CXXFLAGS += -DNO_LIBJPEG
else
CFLAGS += -DHAVE_LIBJPEG
CXXFLAGS += -DHAVE_LIBJPEG
endif

ifdef NO_ZLIB
CFLAGS += -DNO_ZLIB
CXXFLAGS += -DNO_ZLIB
else
CFLAGS += -DHAVE_ZLIB
CXXFLAGS += -DHAVE_ZLIB
LFLAGS_POST += -lz
endif

ifdef NO_READLINE
CFLAGS += -DNO_READLINE
CXXFLAGS += -DNO_READLINE
else
CFLAGS += -DHAVE_READLINE
CXXFLAGS += -DHAVE_READLINE
endif

ifdef NO_STRICT_ALIASING
CFLAGS += -DNO_STRICT_ALIASING
CXXFLAGS += -DNO_STRICT_ALIASING
else
CFLAGS += -DHAVE_STRICT_ALIASING
CXXFLAGS += -DHAVE_STRICT_ALIASING
endif

ifdef CYGWIN
CFLAGS += -DCYGWIN
CXXFLAGS += -DCYGWIN
endif

CFLAGS += -DBOOST_SIGNALS_NO_DEPRECATION_WARNING
CXXFLAGS += -DBOOST_SIGNALS_NO_DEPRECATION_WARNING
all:
